name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        node-version: [20.x]

  unit-tests:
    uses: oclif/github-workflows/.github/workflows/unitTest.yml@main

